AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1 # just added 1 epoch for time consumption and the  more the epoch the better it will be
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01